-- GymGaze Settings Schema Migration
-- Generated by Bolt ⚡ | April 2026

-- profiles extensions
ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS suspended boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS last_login_at timestamptz,
  ADD COLUMN IF NOT EXISTS invited_by uuid REFERENCES profiles(id);

-- invitations
CREATE TABLE IF NOT EXISTS invitations (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  email text NOT NULL,
  role text NOT NULL CHECK (role IN ('admin', 'viewer')),
  token text NOT NULL UNIQUE,
  invited_by uuid REFERENCES profiles(id),
  created_at timestamptz DEFAULT now(),
  accepted_at timestamptz
);

-- portal_config (singleton)
CREATE TABLE IF NOT EXISTS portal_config (
  id int PRIMARY KEY DEFAULT 1,
  owner_widgets jsonb DEFAULT '{"revenue_summary":true,"health_score":true,"campaign_activity":true,"photo_compliance":true,"monthly_report":false}'::jsonb,
  manager_sections jsonb DEFAULT '{"photo_upload":true,"screen_info":true,"venue_stats":true,"contact_support":true}'::jsonb,
  updated_at timestamptz DEFAULT now()
);
INSERT INTO portal_config (id) VALUES (1) ON CONFLICT DO NOTHING;

-- platform_settings (singleton)
CREATE TABLE IF NOT EXISTS platform_settings (
  id int PRIMARY KEY DEFAULT 1,
  platform_name text DEFAULT 'GymGaze',
  support_email text,
  default_gym_revenue_split integer DEFAULT 30,
  invoice_prefix text DEFAULT 'GG-',
  fy_start_month integer DEFAULT 1,
  logo_url text,
  accent_color text DEFAULT '#D4FF4F',
  portal_domain text,
  welcome_message text,
  ga4_measurement_id text,
  updated_at timestamptz DEFAULT now()
);
INSERT INTO platform_settings (id) VALUES (1) ON CONFLICT DO NOTHING;

-- report_scheduler (singleton)
CREATE TABLE IF NOT EXISTS report_scheduler (
  id int PRIMARY KEY DEFAULT 1,
  enabled boolean DEFAULT false,
  delivery_day integer DEFAULT 1,
  recipients jsonb DEFAULT '[]'::jsonb,
  contents jsonb DEFAULT '{"revenue":true,"campaigns":true,"photos":true,"health":true}'::jsonb,
  updated_at timestamptz DEFAULT now()
);
INSERT INTO report_scheduler (id) VALUES (1) ON CONFLICT DO NOTHING;

-- notification_preferences (per admin)
CREATE TABLE IF NOT EXISTS notification_preferences (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  admin_id uuid REFERENCES profiles(id) ON DELETE CASCADE UNIQUE,
  preferences jsonb DEFAULT '{"photo_submitted":true,"photo_approved":false,"photo_rejected":true,"campaign_live":true,"campaign_ended":false,"revenue_added":false,"portal_login":true}'::jsonb,
  updated_at timestamptz DEFAULT now()
);

-- api_credentials (singleton)
CREATE TABLE IF NOT EXISTS api_credentials (
  id int PRIMARY KEY DEFAULT 1,
  api_key_hash text,
  api_key_prefix text,
  webhook_url text,
  webhook_events jsonb DEFAULT '[]'::jsonb,
  ga4_measurement_id text,
  updated_at timestamptz DEFAULT now()
);
INSERT INTO api_credentials (id) VALUES (1) ON CONFLICT DO NOTHING;

-- audit_log
CREATE TABLE IF NOT EXISTS audit_log (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  admin_id uuid REFERENCES profiles(id) ON DELETE SET NULL,
  action text NOT NULL,
  record_type text,
  record_id uuid,
  record_name text,
  metadata jsonb,
  created_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS audit_log_admin_id_idx ON audit_log(admin_id);
CREATE INDEX IF NOT EXISTS audit_log_action_idx ON audit_log(action);
CREATE INDEX IF NOT EXISTS audit_log_created_at_idx ON audit_log(created_at DESC);
