"use client";

import { useState, useEffect, useCallback } from "react";
import { X, Layers, Upload, RefreshCw, AlertTriangle } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { suggestMonthlyImpressions, impressionSuggestionCaption } from "@/lib/staticSiteImpressions";
import { mToCm } from "@/lib/dimensions";
import { generateSiteId } from "@/lib/siteIdGenerator";

interface VenueRow {
  id: string;
  name: string;
  city: string | null;
  monthly_entries?: number | null;
}

interface VenueCodes {
  brand_code: string | null;
  metro_code: string | null;
  venue_code: string | null;
}

export interface StaticSiteRow {
  id: string;
  venue_id: string;
  label: string;
  site_type: string | null;
  location_in_venue: string | null;
  width_cm: number | null;
  height_cm: number | null;
  is_active: boolean | null;
  photo_url: string | null;
  notes: string | null;
  price_per_month: number | null;
  monthly_impressions: number | null;
  pricing_tier: string | null;
  production_cost: number | null;
  flighting_fee: number | null;
  created_at: string;
  venues: { id: string; name: string; city: string | null } | null;
}

interface Props {
  venues: VenueRow[];
  preselectedVenueId?: string;
  onClose: () => void;
  onAdded: (site: StaticSiteRow) => void;
}

export const SITE_TYPE_OPTIONS = [
  { value: "poster_frame", label: "Poster Frame" },
  { value: "banner", label: "Banner" },
  { value: "a_frame", label: "A-Frame" },
  { value: "standee", label: "Standee" },
  { value: "wall_mount", label: "Wall Mount" },
  { value: "window_vinyl", label: "Window Vinyl" },
  { value: "other", label: "Other" },
];

export const LOCATION_OPTIONS = [
  { value: "entrance", label: "Entrance" },
  { value: "gym_floor", label: "Gym Floor" },
  { value: "reception", label: "Reception" },
  { value: "changerooms", label: "Changerooms" },
  { value: "car_park", label: "Car Park" },
  { value: "corridor", label: "Corridor" },
  { value: "other", label: "Other" },
];

export const SITE_TYPE_LABELS: Record<string, string> = Object.fromEntries(
  SITE_TYPE_OPTIONS.map(({ value, label }) => [value, label])
);

export const LOCATION_LABELS: Record<string, string> = Object.fromEntries(
  LOCATION_OPTIONS.map(({ value, label }) => [value, label])
);

export default function AddStaticSiteModal({
  venues,
  preselectedVenueId,
  onClose,
  onAdded,
}: Props) {
  // Venue monthly_entries + codes cache (fetched once on mount)
  const [venueEntries, setVenueEntries] = useState<Record<string, number | null>>({});
  const [venueCodes, setVenueCodes] = useState<Record<string, VenueCodes>>({});
  const [impressionCaption, setImpressionCaption] = useState<string | null>(null);
  const [labelAutoGenerated, setLabelAutoGenerated] = useState(false);

  useEffect(() => {
    async function fetchVenueData() {
      const supabase = createClient();
      const { data } = await supabase
        .from("venues")
        .select("id, monthly_entries, brand_code, metro_code, venue_code");
      if (data) {
        const entriesMap: Record<string, number | null> = {};
        const codesMap: Record<string, VenueCodes> = {};
        data.forEach((v: { id: string; monthly_entries: number | null; brand_code: string | null; metro_code: string | null; venue_code: string | null }) => {
          entriesMap[v.id] = v.monthly_entries ?? null;
          codesMap[v.id] = { brand_code: v.brand_code, metro_code: v.metro_code, venue_code: v.venue_code };
        });
        setVenueEntries(entriesMap);
        setVenueCodes(codesMap);
      }
    }
    fetchVenueData();
  }, []);

  const [form, setForm] = useState({
    venue_id: preselectedVenueId ?? "",
    label: "",
    site_type: "poster_frame",
    location_in_venue: "",
    width_m: "",
    height_m: "",
    notes: "",
    price_per_month: "",
    monthly_impressions: "",
    pricing_tier: "",
    production_cost: "",
    flighting_fee: "",
  });
  const [photo, setPhoto] = useState<File | null>(null);
  const [photoPreview, setPhotoPreview] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [siteCount, setSiteCount] = useState<number>(0);

  function set(key: string, value: string) {
    setForm((prev) => ({ ...prev, [key]: value }));
  }

  // Fetch site count for selected venue (to compute sequence)
  useEffect(() => {
    if (!form.venue_id) { setSiteCount(0); return; }
    const supabase = createClient();
    supabase
      .from("static_sites")
      .select("id", { count: "exact", head: true })
      .eq("venue_id", form.venue_id)
      .then(({ count }) => setSiteCount(count ?? 0));
  }, [form.venue_id]);

  const computeLabel = useCallback((venueId: string, widthM: string, heightM: string): string => {
    const codes = venueCodes[venueId] ?? {};
    const widthCm = widthM !== "" ? Math.round(parseFloat(widthM) * 100) : null;
    const heightCm = heightM !== "" ? Math.round(parseFloat(heightM) * 100) : null;
    return generateSiteId({
      brandCode: codes.brand_code,
      metroCode: codes.metro_code,
      venueCode: codes.venue_code,
      widthCm,
      heightCm,
      sequence: siteCount + 1,
    });
  }, [venueCodes, siteCount]);

  // Auto-generate label when venue/dimensions change (only if not manually edited)
  useEffect(() => {
    if (!form.venue_id) return;
    const generated = computeLabel(form.venue_id, form.width_m, form.height_m);
    setForm((prev) => ({ ...prev, label: generated }));
    setLabelAutoGenerated(true);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [form.venue_id, form.width_m, form.height_m, siteCount, venueCodes]);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError(null);
    if (!form.venue_id) { setError("Please select a venue."); return; }
    setSaving(true);
    try {
      const res = await fetch("/api/static-sites", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          venue_id: form.venue_id,
          label: form.label,
          site_type: form.site_type || "poster_frame",
          location_in_venue: form.location_in_venue || null,
          width_cm: mToCm(form.width_m),
          height_cm: mToCm(form.height_m),
          notes: form.notes || null,
          price_per_month: form.price_per_month !== "" ? parseFloat(form.price_per_month) : null,
          monthly_impressions: form.monthly_impressions !== "" ? parseInt(form.monthly_impressions) : null,
          pricing_tier: form.pricing_tier || null,
          production_cost: form.production_cost !== "" ? parseFloat(form.production_cost) : null,
          flighting_fee: form.flighting_fee !== "" ? parseFloat(form.flighting_fee) : null,
        }),
      });
      if (!res.ok) {
        const body = await res.json();
        throw new Error(body.error ?? "Failed to add site");
      }
      const newSite = await res.json() as StaticSiteRow;
      if (photo) {
        const fd = new FormData();
        fd.append("file", photo);
        await fetch(`/api/static-sites/${newSite.id}/photo`, { method: "POST", body: fd });
      }
      onAdded(newSite);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "Error adding site");
    } finally {
      setSaving(false);
    }
  }

  const inputStyle: React.CSSProperties = {
    background: "rgba(255,255,255,0.05)",
    border: "1px solid rgba(255,255,255,0.10)",
    color: "#fff",
    outline: "none",
    borderRadius: "0.75rem",
    padding: "0.625rem 1rem",
    width: "100%",
    fontSize: "0.875rem",
  };

  const labelStyle: React.CSSProperties = {
    display: "block",
    fontSize: "0.75rem",
    fontWeight: 500,
    color: "#C8C8C8",
    marginBottom: "0.375rem",
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center"
      style={{ backgroundColor: "rgba(0,0,0,0.80)" }}
      onClick={onClose}
    >
      <div
        className="w-full max-w-lg rounded-2xl p-6 overflow-y-auto max-h-[90vh]"
        style={{
          background: "rgba(18,18,18,0.99)",
          border: "1px solid rgba(255,255,255,0.10)",
          backdropFilter: "blur(16px)",
          WebkitBackdropFilter: "blur(16px)",
        }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between mb-5">
          <div className="flex items-center gap-2.5">
            <div
              className="w-8 h-8 rounded-xl flex items-center justify-center"
              style={{ background: "rgba(212,255,79,0.12)" }}
            >
              <Layers size={16} color="#D4FF4F" strokeWidth={2} />
            </div>
            <h3
              className="text-base font-bold text-white"
              style={{ fontFamily: "Inter Tight, sans-serif" }}
            >
              Add Static Site
            </h3>
          </div>
          <button
            onClick={onClose}
            style={{
              background: "rgba(255,255,255,0.06)",
              border: "1px solid rgba(255,255,255,0.10)",
              borderRadius: 8,
              padding: "6px",
              cursor: "pointer",
            }}
          >
            <X size={14} color="#909090" strokeWidth={2} />
          </button>
        </div>

        {error && (
          <div
            className="mb-4 rounded-xl px-4 py-3 text-sm"
            style={{
              backgroundColor: "rgba(239,68,68,0.10)",
              border: "1px solid rgba(239,68,68,0.20)",
              color: "#EF4444",
            }}
          >
            {error}
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-4">
          {/* Venue */}
          {!preselectedVenueId && (
            <div>
              <label style={labelStyle}>Venue *</label>
              <select
                value={form.venue_id}
                onChange={(e) => set("venue_id", e.target.value)}
                required
                style={inputStyle}
              >
                <option value="">Select a venue…</option>
                {venues.map((v) => (
                  <option key={v.id} value={v.id}>
                    {v.name}{v.city ? ` · ${v.city}` : ""}
                  </option>
                ))}
              </select>
            </div>
          )}

          {/* Label */}
          <div>
            <label style={labelStyle}>Site ID *</label>
            <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
              <input
                value={form.label}
                onChange={(e) => { set("label", e.target.value); setLabelAutoGenerated(false); }}
                placeholder="e.g. EF-BCM-BEA-SL1"
                required
                style={{ ...inputStyle, flex: 1 }}
              />
              <button
                type="button"
                title="Regenerate from venue codes"
                onClick={() => {
                  if (!form.venue_id) return;
                  const generated = computeLabel(form.venue_id, form.width_m, form.height_m);
                  set("label", generated);
                  setLabelAutoGenerated(true);
                }}
                style={{
                  flexShrink: 0,
                  padding: "0.625rem",
                  borderRadius: "0.75rem",
                  border: "1px solid rgba(212,255,79,0.3)",
                  background: "rgba(212,255,79,0.08)",
                  color: "#D4FF4F",
                  cursor: "pointer",
                  display: "flex",
                  alignItems: "center",
                }}
              >
                <RefreshCw size={14} strokeWidth={2} />
              </button>
            </div>
            {form.venue_id && labelAutoGenerated && (
              <p style={{ fontSize: "0.7rem", color: "#888", marginTop: "0.35rem" }}>
                Auto-generated. Edit if needed.
              </p>
            )}
            {form.venue_id && (() => {
              const codes = venueCodes[form.venue_id];
              const missingCodes = codes && !codes.brand_code && !codes.metro_code && !codes.venue_code;
              return missingCodes ? (
                <div style={{ display: "flex", alignItems: "center", gap: 6, marginTop: "0.4rem", padding: "0.4rem 0.75rem", borderRadius: "0.5rem", background: "rgba(251,191,36,0.10)", border: "1px solid rgba(251,191,36,0.25)" }}>
                  <AlertTriangle size={12} color="#FBB724" strokeWidth={2} />
                  <span style={{ fontSize: "0.7rem", color: "#FBB724" }}>
                    Venue codes not set — using placeholders. Set them in Venue Settings.
                  </span>
                </div>
              ) : null;
            })()}
          </div>

          {/* Site Type */}
          <div>
            <label style={labelStyle}>Site Type</label>
            <select
              value={form.site_type}
              onChange={(e) => set("site_type", e.target.value)}
              style={inputStyle}
            >
              {SITE_TYPE_OPTIONS.map((o) => (
                <option key={o.value} value={o.value}>{o.label}</option>
              ))}
            </select>
          </div>

          {/* Location in venue */}
          <div>
            <label style={labelStyle}>Location in Venue</label>
            <select
              value={form.location_in_venue}
              onChange={(e) => set("location_in_venue", e.target.value)}
              style={inputStyle}
            >
              <option value="">Select location…</option>
              {LOCATION_OPTIONS.map((o) => (
                <option key={o.value} value={o.value}>{o.label}</option>
              ))}
            </select>
          </div>

          {/* Width + Height in meters */}
          <div>
            <label style={labelStyle}>Dimensions</label>
            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="block text-xs mb-1" style={{ color: "#777" }}>Width (m)</label>
                <input type="number" min={0} step={0.01} value={form.width_m} onChange={(e) => set("width_m", e.target.value)} placeholder="e.g. 0.60" style={inputStyle} />
              </div>
              <div>
                <label className="block text-xs mb-1" style={{ color: "#777" }}>Height (m)</label>
                <input type="number" min={0} step={0.01} value={form.height_m} onChange={(e) => set("height_m", e.target.value)} placeholder="e.g. 0.90" style={inputStyle} />
              </div>
            </div>
          </div>

          {/* Pricing fields */}
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label style={labelStyle}>Rate per Month (R)</label>
              <input
                type="number"
                min={0}
                step={1}
                value={form.price_per_month}
                onChange={(e) => set("price_per_month", e.target.value)}
                placeholder="e.g. 3500"
                style={inputStyle}
              />
            </div>
            <div>
              <label style={labelStyle}>Monthly Impressions</label>
              <input
                type="number"
                min={0}
                step={1}
                value={form.monthly_impressions}
                onChange={(e) => {
                  set("monthly_impressions", e.target.value);
                  setImpressionCaption(null);
                }}
                placeholder="e.g. 12000"
                style={inputStyle}
              />
            </div>
          </div>
          {/* One-time cost fields */}
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label style={labelStyle}>Production Cost (R)</label>
              <input
                type="number"
                min={0}
                step={1}
                value={form.production_cost}
                onChange={(e) => set("production_cost", e.target.value)}
                placeholder="e.g. 2500"
                style={inputStyle}
              />
            </div>
            <div>
              <label style={labelStyle}>Flighting Fee (R)</label>
              <input
                type="number"
                min={0}
                step={1}
                value={form.flighting_fee}
                onChange={(e) => set("flighting_fee", e.target.value)}
                placeholder="e.g. 800"
                style={inputStyle}
              />
            </div>
          </div>
          <p style={{ fontSize: "0.7rem", color: "#888", marginTop: "-0.5rem" }}>One-time costs added to campaign investment</p>
          {/* Suggest from footfall */}
          {(() => {
            const monthlyEntries = form.venue_id ? (venueEntries[form.venue_id] ?? null) : null;
            const canSuggest = !!form.venue_id && !!form.location_in_venue && !!monthlyEntries;
            return (
              <div>
                <button
                  type="button"
                  disabled={!canSuggest}
                  onClick={() => {
                    if (!canSuggest || !monthlyEntries) return;
                    const suggested = suggestMonthlyImpressions(monthlyEntries, form.location_in_venue);
                    if (suggested !== null) {
                      set("monthly_impressions", suggested.toString());
                      setImpressionCaption(impressionSuggestionCaption(monthlyEntries, form.location_in_venue));
                    }
                  }}
                  style={{
                    fontSize: "0.75rem",
                    fontWeight: 600,
                    padding: "0.375rem 0.875rem",
                    borderRadius: "0.5rem",
                    border: "1px solid rgba(212,255,79,0.3)",
                    background: canSuggest ? "rgba(212,255,79,0.10)" : "rgba(255,255,255,0.04)",
                    color: canSuggest ? "#D4FF4F" : "#555",
                    cursor: canSuggest ? "pointer" : "not-allowed",
                  }}
                >
                  ⚡ Suggest from footfall
                </button>
                {impressionCaption && (
                  <p style={{ fontSize: "0.7rem", color: "#888", marginTop: "0.375rem", lineHeight: 1.5 }}>
                    {impressionCaption}
                  </p>
                )}
              </div>
            );
          })()}

          <div>
            <label style={labelStyle}>Pricing Tier (optional)</label>
            <select
              value={form.pricing_tier}
              onChange={(e) => set("pricing_tier", e.target.value)}
              style={inputStyle}
            >
              <option value="">Select tier…</option>
              <option value="Premium">Premium</option>
              <option value="Standard">Standard</option>
              <option value="Entry">Entry</option>
            </select>
          </div>

          {/* Photo upload */}
          <div>
            <label style={labelStyle}>Photo (optional)</label>
            {photoPreview ? (
              <div className="relative rounded-xl overflow-hidden" style={{ aspectRatio: "16/9" }}>
                <img src={photoPreview} alt="preview" className="w-full h-full object-cover" />
                <button
                  type="button"
                  onClick={() => { setPhoto(null); setPhotoPreview(null); }}
                  className="absolute top-2 right-2 p-1.5 rounded-lg"
                  style={{ background: "rgba(0,0,0,0.6)", color: "#fff" }}
                >
                  <X size={13} strokeWidth={2} />
                </button>
              </div>
            ) : (
              <label
                className="flex flex-col items-center justify-center gap-2 w-full rounded-xl cursor-pointer"
                style={{ background: "rgba(255,255,255,0.04)", border: "1px dashed rgba(255,255,255,0.15)", padding: "20px" }}
              >
                <Upload size={18} color="#555" strokeWidth={2} />
                <span className="text-xs" style={{ color: "#666" }}>Upload a photo of the placement</span>
                <input
                  type="file"
                  accept="image/*"
                  className="hidden"
                  onChange={(e) => {
                    const f = e.target.files?.[0] ?? null;
                    setPhoto(f);
                    if (f) setPhotoPreview(URL.createObjectURL(f));
                  }}
                />
              </label>
            )}
          </div>

          {/* Notes */}
          <div>
            <label style={labelStyle}>Notes (optional)</label>
            <textarea
              value={form.notes}
              onChange={(e) => set("notes", e.target.value)}
              placeholder="Any additional notes…"
              rows={3}
              style={{ ...inputStyle, resize: "vertical", minHeight: "80px" }}
            />
          </div>

          {/* Actions */}
          <div className="flex gap-3 pt-2">
            <button
              type="button"
              onClick={onClose}
              className="flex-1 py-2.5 rounded-xl text-sm"
              style={{
                border: "1px solid rgba(255,255,255,0.10)",
                color: "#C8C8C8",
                background: "transparent",
                cursor: "pointer",
              }}
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={saving}
              className="flex-1 py-2.5 rounded-xl text-sm font-semibold"
              style={{
                backgroundColor: saving ? "#3a3a3a" : "#D4FF4F",
                color: saving ? "#888" : "#0A0A0A",
                border: "none",
                cursor: saving ? "wait" : "pointer",
              }}
            >
              {saving ? "Saving…" : "Add Site"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
